# Generated by Django 5.2.4 on 2025-07-10 06:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('control1_promedio', models.FloatField(blank=True, null=True)),
                ('control1_desviacion', models.FloatField(blank=True, null=True)),
                ('control2_promedio', models.FloatField(blank=True, null=True)),
                ('control2_desviacion', models.FloatField(blank=True, null=True)),
                ('control3_promedio', models.FloatField(blank=True, null=True)),
                ('control3_desviacion', models.FloatField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
